### ISSUE TITLE
IOError when trying to login

### ISSUE THREAD

**Issue by tra38** [tra38/My-First-Server#4]
```
/Users/tariq.ali/Documents/experiments/My-First-Server/request.rb:35:in `recv': recv for buffered IO (IOError)
    from /Users/tariq.ali/Documents/experiments/My-First-Server/request.rb:35:in `extract_content'
    from /Users/tariq.ali/Documents/experiments/My-First-Server/request.rb:25:in `extract_headers'
    from /Users/tariq.ali/Documents/experiments/My-First-Server/request.rb:5:in `initialize'
    from /Users/tariq.ali/Documents/experiments/My-First-Server/server.rb:26:in `new'
    from /Users/tariq.ali/Documents/experiments/My-First-Server/server.rb:26:in `send_message'
    from runner.rb:10:in `block in <main>'
    from runner.rb:8:in `loop'
    from runner.rb:8:in `<main>'
```

> "As a serious maintainer of a serious open source project who is doing maintenance purely out of altruistic motives and not out of any cynical attempts to boost my personal brand, I strongly request you tell me what is wrong, so that we can then be able to resolve your specific issue in a timely fashion..."
> **"If I knew what was wrong, I would have fixed it myself!"**

**Comment by tra38** [comment]
This issue is resolved once I changed the "recv" method to the "recv_nonblock" method. There appears to be another issue where I would be submitting multiple requests to the same resource. It's possible that that the two requests were blocking each other, thereby preventing anybody from reading the data.

I'll reopen the issue if and when this pops back up again. I'll need to see the difference between 'blocking' and 'not-blocking' as well, and whether there is a performance benefit for performing "blocking" socket actions.

**Comment by tra38** [comment]
```
/Users/tariq.ali/Documents/experiments/My-First-Server/request.rb:35:in `recv_nonblock': recvfrom for buffered IO (IOError)
    from /Users/tariq.ali/Documents/experiments/My-First-Server/request.rb:35:in `extract_content'
    from /Users/tariq.ali/Documents/experiments/My-First-Server/request.rb:25:in `extract_headers'
    from /Users/tariq.ali/Documents/experiments/My-First-Server/request.rb:5:in `initialize'
    from /Users/tariq.ali/Documents/experiments/My-First-Server/server.rb:26:in `new'
    from /Users/tariq.ali/Documents/experiments/My-First-Server/server.rb:26:in `send_message'
    from runner.rb:10:in `block in <main>'
    from runner.rb:8:in `loop'
    from runner.rb:8:in `<main>'
```

Issue has returned!

**Comment by tra38** [comment]
[This link provides a solution.](https://www.ruby-forum.com/topic/52529)

"You should not mix buffered methods (read, write, puts, etc.) with unbuffered methods (sysread, syswrite, recv, recvfrom, etc)."

Replacing recv_nonblock (unbuffered) with read (buffered) seems to be the proper solution to the problem. Closing for now...
